version: '3.5'

services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    networks:
      - backend
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      args:
        UID: ${U_ID:-1000}
    volumes:
      - ./docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      #- ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini # Linux users
      - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini # MacOS users
      - ./:/var/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - 40000:3306
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - backend

volumes:
  database-data:

networks:
  backend:
